### ISSUE TITLE
Bring back library.bib for making a pool of papers

### ISSUE THREAD

**Issue by lepisma** [Vernacular-ai/paper-reading#14]
Jaydeep, you can do PRs once this is done

@jaydeepborkar

**Comment by jaydeepborkar** [comment]
> Jaydeep, you can do PRs once this is done
> 
> @jaydeepborkar

@lepisma, sure. Looking forward to it!

**Comment by lepisma** [comment]
Added sample bib files here -> https://github.com/Vernacular-ai/paper-reading/tree/master/library

They are not complete but we can start putting entries there. Closing this issue.
